# --- COLORES (Monocromo / Escala de grises) ---
foreground              #E6E6E6
background              #0D0D0D
selection_foreground    #000000
selection_background    #FFFFFF
url_color                #FFFFFF

# Pestañas
active_tab_foreground   #000000
active_tab_background   #FFFFFF
inactive_tab_foreground #999999
inactive_tab_background #1A1A1A
tab_bar_background      #000000

# Los 16 colores del terminal (rampa de grises, aclarada para más contraste con el fondo)
color0  #464646
color8  #525252
color1  #5F5F5F
color9  #6B6B6B
color2  #777777
color10 #848484
color3  #909090
color11 #9C9C9C
color4  #A9A9A9
color12 #B5B5B5
color5  #C1C1C1
color13 #CECECE
color6  #DADADA
color14 #E6E6E6
color7  #F3F3F3
color15 #FFFFFF
