# --- EFECTOS VISUALES Y VENTANA ---
background_opacity 1
dynamic_background_opacity yes
window_padding_width 4
confirm_os_window_close 0
hide_window_decorations yes

# --- LAYOUTS MULTIPLES ---
enabled_layouts splits, tall, fat, grid, stack
