# ==============================================================================
# CONFIGURACIÓN COMPLETA DE HYPRLAND
# ==============================================================================

# Cargar configuraciones separadas

# Cargar configuraciones separadas


source = ./conf/autostart.conf
source = ./conf/monitors.conf
source = ./conf/environment.conf
source = ./conf/input.conf
source = ./conf/general.conf
source = ./conf/windowrules.conf
source = ./conf/keybinds.conf
