# ------------------------------------------------------------------------------
# HYPRIDLE — bloqueo automático por inactividad
# 5 min sin actividad -> hyprlock. 30s después -> apaga pantalla (DPMS).
# Cambiá los "timeout" (en segundos) si querés otro tiempo de espera.
# ------------------------------------------------------------------------------

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# bloquear a los 5 minutos de inactividad
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# apagar la pantalla 30s después de bloquear (si seguís sin tocar nada)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
