# ------------------------------------------------------------------------------
# 2. INICIO AUTOMÁTICO (Autostart)
# ------------------------------------------------------------------------------
exec-once = waybar & hyprpaper & swaync
exec-once = ~/.config/hypr/scripts/wallpaper.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/detect_machine.sh
exec-once = nm-applet --indicator
# Gestor de autenticación (Necesario para apps que piden contraseña de root)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Lanzar en el arranque directamente al espacio oculto
exec-once = [workspace special:music silent] spotify
exec-once = bash -c 'sleep 5 && easyeffects '