# ------------------------------------------------------------------------------
# 5. APARIENCIA GENERAL Y BORDES
# ------------------------------------------------------------------------------
general {
    gaps_in = 5
    gaps_out = 0,0,10,0 # top,right,bottom,left: pegado a waybar, izquierda y derecha
    border_size = 2
    
    # Colores de bordes (escala de grises)
    col.active_border = rgba(ffffffee) rgba(808080ee) 45deg
    col.inactive_border = rgba(333333aa)

    layout = dwindle # Alternativa: master
}


# ------------------------------------------------------------------------------
# 6. DECORACIÓN (Desenfoque, Sombras y Esquinas redondeadas)
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# 8. AJUSTES DE LAYOUT (Dwindle)
# ------------------------------------------------------------------------------
dwindle {
    force_split = 2 # 0 -> sigue el ratón, 1 -> siempre a la izquierda/arriba, 2 -> siempre a la derecha/abajo
    preserve_split = true 
}


# ------------------------------------------------------------------------------
# 9. MISCELÁNEOS
# ------------------------------------------------------------------------------
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

