# ------------------------------------------------------------------------------
# 4. ENTRADA (Teclado y Ratón)
# ------------------------------------------------------------------------------
input {
    kb_layout = us,es # Cambia a 'latam' si usas teclado latinoamericano
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true # Scroll como en los teléfonos
        tap-to-click = true
    }

    sensitivity = 0 # -1.0 a 1.0, 0 es por defecto
}

device {
    name = elan2513:00-04f3:4038
    enabled = false
}
