# ------------------------------------------------------------------------------
# 11. ATAJOS DE TECLADO (Keybinds)
# ------------------------------------------------------------------------------
$mainMod = SUPER

# Categorized Keybinds
source = ~/.config/hypr/conf/keybinds/apps.conf
source = ~/.config/hypr/conf/keybinds/workspaces.conf
source = ~/.config/hypr/conf/keybinds/window.conf
source = ~/.config/hypr/conf/keybinds/system.conf
source = ~/.config/hypr/conf/keybinds/media.conf
