# ------------------------------------------------------------------------------
# 1. MONITORES
# ------------------------------------------------------------------------------
# Detecta la resolución y tasa de refresco preferida de forma automática

#monitor=,preferred,auto,1.50
