# ------------------------------------------------------------------------------
# 10. REGLAS DE VENTANAS (Window Rules)
# ------------------------------------------------------------------------------
# Fuerza a que ciertas apps se abran siempre en modo flotante

windowrule {
    name = easyeffects-special

    match:class = ^(com.github.wwmm.easyeffects)$

    workspace = special:audio silent
}