# ------------------------------------------------------------------------------
# 10. REGLAS DE VENTANAS (Window Rules)
# ------------------------------------------------------------------------------
# Fuerza a que ciertas apps se abran siempre en modo flotante

# Audio apps viven en special:music
windowrule {
    name = spotify-special

    match:class = ^(Spotify)$

    workspace = special:music silent
}

windowrule {
    name = easyeffects-special

    match:class = ^(com.github.wwmm.easyeffects)$

    workspace = special:audio silent
}