# -----------------------------------------------------
# Apps Config
# -----------------------------------------------------

bind = $mainMod, Return, exec, kitty
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod SHIFT, R, exec, ~/.config/rofi/scripts/menu.sh
bind = $mainMod, W, exec, ~/Bully-ye/wallpaper-carousel/run-carousel.sh
bind = $mainMod, B, exec, firefox
bind = $mainMod, S, togglespecialworkspace, music
bind = $mainMod, E, togglespecialworkspace, audio
bind = $mainMod, Q, exec, ~/Bully-ye/calculadora/run.sh

# Rofi scripts
bind = $mainMod, N,        exec, ~/.config/rofi/scripts/network.sh
bind = $mainMod SHIFT, B,  exec, ~/.config/rofi/scripts/bluetooth.sh
bind = $mainMod, K,        exec, ~/.config/rofi/scripts/clipboard.sh
bind = $mainMod SHIFT, K,  exec, ~/.config/rofi/scripts/bitwarden.sh
bind = $mainMod, X,        exec, ~/.config/rofi/scripts/powermenu.sh
bind = $mainMod, H,        exec, ~/.config/rofi/scripts/ssh.sh
bind = $mainMod, G,        exec, ~/.config/rofi/scripts/workspace.sh
bind = $mainMod SHIFT, V,  exec, ~/.config/rofi/scripts/volume.sh
# bind = $mainMod, ..., exec, ~/.config/rofi/scripts/brightness.sh

