# -----------------------------------------------------
# System Config
# -----------------------------------------------------

bind = $mainMod SHIFT, M, exit, 
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod SHIFT, Q, exec, shutdown now 
bind = $mainMod, L, exec, ~/Bully-ye/hypr/scripts/cambioTeclado.sh


