# -----------------------------------------------------
# System Config
# -----------------------------------------------------

bind = $mainMod SHIFT, M, exit, 
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod SHIFT, Q, exec, shutdown now 
bind = $mainMod, L, exec, ~/.config/hypr/scripts/cambioTeclado.sh
bind = $mainMod SHIFT, L, exec, hyprlock


