# -----------------------------------------------------
# Window Management Config
# -----------------------------------------------------

bind = $mainMod, C, killactive, 
bind = $mainMod, V, togglefloating, 
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, layoutmsg, togglesplit # dwindle
bind = $mainMod, F, fullscreen,

# Foco de ventanas (Con flechas)
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u # Reemplazado por control de volumen
bind = $mainMod, down, movefocus, d # Reemplazado por control de volumen

# Mover ventanas de posición (SUPER + SHIFT + flechas)
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Mover y redimensionar ventanas con el ratón
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# cambiar de horientacion 
bind = $mainMod, Tab, cyclenext, direction
bind = $mainMod, O, layoutmsg, togglesplit
bind = $mainMod, I, swapnext

# Toggle modo austero (sin bordes/gaps)
bind = $mainMod, A, exec, ~/Bully-ye/hypr/scripts/toggle_austere.sh
